development:
  adapter: postgresql
  encoding: unicode
  database: ear_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: ear_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: ear_production
  pool: 5
  host: localhost
